# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7ff9ef0a7a141190c6ed10b572c4553e1d994b1570872abdcffd072c95b6589539fabac33a37a4ba071697c7e860cca638d0872814de87c84d5b610ee8af807

test:
  secret_key_base: ff2b306f8c8edfbaf21028365c748777f1567b3a0d74f6dc7ccba5fc592654d7dc77a9ac386ecdcfdf00d7c8c2660d34af2fb6153133d57b42c4e82ef07a2fa7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
